# Generated by Django 3.2 on 2021-04-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='User',
            new_name='user',
        ),
    ]
